import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

// Color palette
export const COLORS = {
  primary: '#2D6A4F',
  primaryDark: '#1B5E3F',
  primaryLight: '#48BB78',
  secondary: '#9FD5CD',
  background: '#F0F4F8',
  surface: '#FFFFFF',
  error: '#E53E3E',
  warning: '#ED8936',
  success: '#48BB78',
  text: '#2D3436',
  textSecondary: '#636E72',
  border: '#E2E8F0',
  overlay: 'rgba(0, 0, 0, 0.7)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  coverContainer: {
    position: 'relative',
    height: 120,
    backgroundColor: '#2D6A4F',
  },
  coverImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  coverOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 5,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  subtitle: {
    fontSize: 14,
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  // Modern Pantry Card Styles
  pantryHeaderSection: {
    backgroundColor: '#0F3B2F',
    background: 'linear-gradient(135deg, #064E3B 0%, #052E22 50%, #041F17 100%)',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 8,
    width: '100%',
  },
  pantryBackgroundOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderRadius: 0,
  },
  pantryBackgroundCircle1: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    top: '10%',
    right: -30,
    opacity: 0.6,
  },
  pantryBackgroundCircle2: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    bottom: '15%',
    left: -15,
    opacity: 0.5,
  },
  pantryBackgroundCircle3: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    top: '60%',
    right: '20%',
    opacity: 0.7,
  },
  pantryHeaderCard: {
    backgroundColor: '#052E22',
    borderRadius: 16,
    padding: 16,
    shadowColor: 'rgba(0, 0, 0, 0.3)',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    zIndex: 10,
    position: 'relative',
    marginHorizontal: 8,
  },
  welcomeHeaderSection: {
    backgroundColor: '#0F3B2F',
    paddingHorizontal: 0,
    paddingTop: 40,
    paddingBottom: 50,
    position: 'relative',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
  },
  gradientOverlay1: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '40%',
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderRadius: 0,
  },
  gradientOverlay2: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '30%',
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderRadius: 0,
  },
  gradientOverlay3: {
    position: 'absolute',
    top: '20%',
    right: -50,
    width: 150,
    height: 150,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderRadius: 75,
  },
  welcomeHeaderContent: {
    alignItems: 'center',
    zIndex: 10,
    position: 'relative',
  },
  welcomeHeaderTitle: {
    fontSize: 34,
    fontWeight: '600',
    color: '#FFFFFF',
    letterSpacing: 2,
    fontFamily: 'System',
    textAlign: 'center',
    lineHeight: 44,
    opacity: 1,
    textTransform: 'capitalize',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
  },
  welcomeContainer: {
    backgroundColor: '#F1F5F9',
    flex: 1,
    paddingTop: 60,
    paddingBottom: 60,
    position: 'relative',
    overflow: 'hidden',
  },
  backgroundDecor1: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: '#E0F2FE',
    top: -50,
    right: -50,
    opacity: 0.6,
  },
  backgroundDecor2: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: '#ECFDF5',
    bottom: -30,
    left: -40,
    opacity: 0.5,
  },
  backgroundDecor3: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#FEF3F2',
    top: '40%',
    right: -30,
    opacity: 0.4,
  },
  backgroundDecor4: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#EDE9FE',
    top: '20%',
    left: -20,
    opacity: 0.5,
  },
  backgroundDecor5: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#FEF7FF',
    bottom: '20%',
    right: -40,
    opacity: 0.3,
  },
  backgroundDecor6: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#F0F9FF',
    top: '60%',
    left: -10,
    opacity: 0.6,
  },
  backgroundDecor7: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#FFFBEB',
    top: '10%',
    left: '30%',
    opacity: 0.4,
  },
  backgroundDecor8: {
    position: 'absolute',
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#F3E8FF',
    bottom: '30%',
    left: '80%',
    opacity: 0.5,
  },
  backgroundDecor9: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#ECFCCB',
    top: '70%',
    right: '70%',
    opacity: 0.3,
  },
  backgroundDecor10: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FEE2E2',
    top: '25%',
    right: '15%',
    opacity: 0.6,
  },
  backgroundDecor11: {
    position: 'absolute',
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#F0F9FF',
    bottom: '10%',
    left: '50%',
    opacity: 0.2,
  },
  modernPantryCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 20,
    padding: 24,
    marginHorizontal: 16,
    marginVertical: 8,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  pantryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingTop: 4,
  },
  pantryMainInfo: {
    flex: 1,
    alignItems: 'flex-start',
    paddingVertical: 0,
    paddingRight: 16,
  },
  pantryActions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    marginTop: 4,
  },
  modernPantryName: {
    fontSize: 32,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 12,
    letterSpacing: -0.8,
    textAlign: 'left',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    lineHeight: 38,
  },
  modernOwnerBadge: {
    fontSize: 11,
    fontWeight: '800',
    color: '#064E3B',
    backgroundColor: 'rgba(167, 243, 208, 0.95)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 16,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 3,
    alignSelf: 'flex-start',
    backdropFilter: 'blur(10px)',
  },
  modernMemberCount: {
    fontSize: 15,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'left',
    letterSpacing: 0.3,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    lineHeight: 20,
  },
  modernManageButton: {
    backgroundColor: '#F7FAFC',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignSelf: 'flex-start',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  modernManageContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  modernManageIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  modernManageText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2D3748',
  },
  modernNotificationDot: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#EA580C',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    shadowColor: '#EA580C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  modernNotificationCount: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  circularLeaveButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#DC2626',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#DC2626',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  circularManageButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    backdropFilter: 'blur(15px)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 8,
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  circularButtonIcon: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  whiteBellIcon: {
    fontSize: 18,
    color: '#A7F3D0',
    fontWeight: 'bold',
  },
  modernLeaveButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(248, 113, 113, 0.9)',
    backdropFilter: 'blur(10px)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(248, 113, 113, 0.4)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 6,
  },
  modernLeaveIcon: {
    fontSize: 20,
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '300',
    lineHeight: 20,
  },
  modernLogButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(34, 197, 94, 0.9)', // Green for logs
    backdropFilter: 'blur(10px)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: 'rgba(34, 197, 94, 0.4)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    marginLeft: 10,
  },
  modernLogIcon: {
    fontSize: 22,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  welcomeScreen: {
    alignItems: 'center',
    paddingVertical: 50,
    paddingHorizontal: 32,
    minHeight: 520,
    justifyContent: 'center',
    zIndex: 1,
  },
  welcomeIconContainer: {
    marginBottom: 60,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 44,
    minHeight: 44,
  },
  welcomeIcon: {
    width: 140,
    height: 140,
    backgroundColor: '#F0FDF4',
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 2,
    borderColor: '#E6FFFA',
  },
  welcomeIconText: {
    fontSize: 50,
    lineHeight: 50,
  },
  welcomeIconImage: {
    width: 90,
    height: 90,
    backgroundColor: 'transparent',
  },
  welcomeIconFallback: {
    fontSize: 60,
    fontWeight: 'bold',
    color: '#10B981',
  },
  leafIcon: {
    width: 60,
    height: 60,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leafPart1: {
    position: 'absolute',
    width: 25,
    height: 40,
    backgroundColor: '#064E3B',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    borderBottomLeftRadius: 25,
    transform: [{ rotate: '-20deg' }],
    left: 10,
    top: 5,
  },
  leafPart2: {
    position: 'absolute',
    width: 20,
    height: 30,
    backgroundColor: '#10B981',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    transform: [{ rotate: '30deg' }],
    right: 8,
    top: 10,
  },
  leafPart3: {
    position: 'absolute',
    width: 18,
    height: 25,
    backgroundColor: '#34D399',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    transform: [{ rotate: '60deg' }],
    right: 5,
    bottom: 8,
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1F2937',
    marginBottom: 12,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  welcomeSubtitle: {
    fontSize: 17,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 50,
    lineHeight: 24,
    fontWeight: '500',
  },
  welcomeActions: {
    width: '100%',
    alignItems: 'center',
    gap: 24,
    marginTop: 20,
  },
  welcomeCreateButton: {
    backgroundColor: '#10B981',
    paddingVertical: 20,
    paddingHorizontal: 32,
    borderRadius: 24,
    width: '85%',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  createButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  createButtonIcon: {
    fontSize: 22,
    color: '#FFFFFF',
    marginRight: 10,
    fontWeight: 'bold',
  },
  welcomeCreateText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 1,
    textAlign: 'center',
  },
  welcomeSearchButton: {
    backgroundColor: '#064E3B',
    paddingVertical: 20,
    paddingHorizontal: 28,
    borderRadius: 24,
    width: '85%',
    borderWidth: 0,
    shadowColor: '#064E3B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  searchButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  searchButtonIcon: {
    fontSize: 18,
    color: '#FFFFFF',
    marginRight: 8,
  },
  welcomeSearchText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  searchPantryButton: {
    backgroundColor: '#10B981',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  searchPantryText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  searchContainer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
  },
  searchResultsContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  pantryResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    padding: 16,
    marginVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  pantryResultInfo: {
    flex: 1,
  },
  pantryNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  pantryResultName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    flex: 1,
  },
  ownerBadge: {
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 8,
  },
  ownedPantryItem: {
    borderColor: '#10B981',
    backgroundColor: '#F0FDF4',
  },
  pantryResultSubtext: {
    fontSize: 13,
    color: '#6B7280',
  },
  joinArrow: {
    fontSize: 18,
    color: '#10B981',
    fontWeight: 'bold',
  },
  ownerArrow: {
    color: '#059669',
  },
  emptySearchState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptySearchText: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
  },
  requestsContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  requestItem: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    marginVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  requestInfo: {
    marginBottom: 12,
  },
  requestName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
  },
  requestEmail: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 4,
  },
  requestDate: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  requestActions: {
    flexDirection: 'row',
    gap: 12,
  },
  approveButton: {
    flex: 1,
    backgroundColor: '#10B981',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  approveButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  rejectButton: {
    flex: 1,
    backgroundColor: '#EA580C',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  rejectButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  emptyRequestsState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyRequestsText: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
  },
  modalCloseButton: {
    backgroundColor: '#10B981',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  modalCloseText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  manageButton: {
    backgroundColor: '#2D6A4F',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    position: 'relative',
  },
  manageButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  manageButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  requestNotificationBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#FF4444',
    borderRadius: 16,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  requestNotificationText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
  },
  requestCountBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    minWidth: 14,
    height: 14,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  requestCountText: {
    color: '#FF4444',
    fontSize: 9,
    fontWeight: '700',
    textAlign: 'center',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: 20,
    marginTop: 25,
    marginBottom: 25,
    gap: 25,
  },
  addButton: {
    backgroundColor: '#0A4B4C',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0A4B4C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  scanButton: {
    backgroundColor: '#9FD5CD',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#9FD5CD',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  refreshButton: {
    backgroundColor: '#22C55E',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  refreshButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
  },
  cameraIcon: {
    position: 'relative',
    width: 28,
    height: 28,
  },
  cameraBody: {
    position: 'absolute',
    width: 28,
    height: 20,
    backgroundColor: '#0A4B4C',
    borderRadius: 4,
    top: 4,
  },
  cameraLens: {
    position: 'absolute',
    width: 12,
    height: 12,
    backgroundColor: '#F7F9FC',
    borderRadius: 6,
    top: 8,
    left: 8,
    borderWidth: 2,
    borderColor: '#0A4B4C',
  },
  refreshIcon: {
    width: 24,
    height: 24,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    borderRadius: 12,
    borderTopColor: 'transparent',
    transform: [{ rotate: '45deg' }],
  },
  refreshArrow: {
    position: 'absolute',
    top: -2,
    right: -1,
    width: 0,
    height: 0,
    borderLeftWidth: 4,
    borderRightWidth: 4,
    borderBottomWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#FFFFFF',
    transform: [{ rotate: '-45deg' }],
  },
  statsBar: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D6A4F',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 12,
    color: '#718096',
    fontWeight: '500',
  },
  statDivider: {
    width: 1,
    backgroundColor: '#E2E8F0',
    marginHorizontal: 16,
  },
  contentWrapper: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#F8F9FA',
  },
  contentContainer: {
    flex: 1,
    paddingTop: 20,
  },
  contentBackgroundCircle1: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    top: 50,
    right: -40,
    opacity: 0.8,
  },
  contentBackgroundCircle2: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    top: 200,
    left: -30,
    opacity: 0.7,
  },
  contentBackgroundCircle3: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    top: 350,
    right: -60,
    opacity: 0.6,
  },
  contentBackgroundCircle4: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    bottom: 100,
    left: -40,
    opacity: 0.7,
  },
  contentBackgroundCircle5: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    bottom: 250,
    right: 20,
    opacity: 0.6,
  },
  categoriesContainer: {
    paddingHorizontal: 12,
  },
  categoryCard: {
    marginHorizontal: 4,
    marginBottom: 12,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
  },
  categoryHeader: {
    padding: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F8FAFC',
  },
  categoryTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  categoryIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  categoryIconText: {
    fontSize: 20,
  },
  categoryInfo: {
    flex: 1,
  },
  categoryTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A202C',
    marginBottom: 2,
  },
  categorySubtitle: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '500',
  },
  itemsScrollView: {
    paddingHorizontal: 12,
  },
  itemsScrollContent: {
    paddingHorizontal: 1,
    paddingVertical: 4,
  },
  itemIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  itemIcon: {
    fontSize: 16,
  },
  expiryLabel: {
    fontSize: 7,
    fontWeight: '600',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 6,
    textAlign: 'center',
    marginTop: 2,
    overflow: 'hidden',
  },
  itemTouchable: {
    width: '100%',
    height: '100%',
  },
  modernItemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    margin: 4,
    width: 108,
    height: 90,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemContent: {
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  itemHeader: {
    marginBottom: 6,
    alignItems: 'center',
    position: 'relative',
  },
  itemName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1A202C',
    lineHeight: 13,
    textAlign: 'center',
    marginTop: 6,
  },
  itemDetails: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  itemAmount: {
    fontSize: 9,
    color: '#A0AEC0',
    fontWeight: '400',
    textAlign: 'center',
    marginTop: 2,
  },
  statusCircle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    position: 'absolute',
    top: -2,
    right: -2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  welcomeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
    minHeight: 500,
  },
  welcomeContent: {
    alignItems: 'center',
    maxWidth: 340,
    width: '100%',
  },
  welcomeIconShape: {
    width: 40,
    height: 40,
    backgroundColor: '#22C55E',
    borderRadius: 12,
  },
  welcomeTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1F2937',
    marginBottom: 8,
    textAlign: 'center',
  },
  welcomeSubtitle: {
    fontSize: 18,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 24,
  },
  welcomeFeatures: {
    width: '100%',
    marginBottom: 40,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  featureIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  featureDot: {
    width: 8,
    height: 8,
    backgroundColor: '#22C55E',
    borderRadius: 4,
  },
  featureText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    flex: 1,
  },
  primaryButton: {
    backgroundColor: '#22C55E',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    marginBottom: 20,
    minWidth: 200,
  },
  primaryButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  helpText: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 20,
  },
  essentialsContainer: {
    marginTop: 24,
  },
  essentialsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 4,
  },
  essentialsSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 16,
    lineHeight: 20,
  },
  essentialsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  essentialButton: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    margin: 4,
    minWidth: 80,
    alignItems: 'center',
  },
  essentialButtonSelected: {
    backgroundColor: '#0A4B4C',
    borderColor: '#0A4B4C',
  },
  essentialButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
  },
  essentialButtonTextSelected: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  selectedItemsCount: {
    fontSize: 14,
    color: '#22C55E',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#2D6A4F',
  },
  bottomPadding: {
    height: 120,
  },
  
  // Category Filter Tabs Styles
  categoryTabsContainer: {
    marginVertical: 15,
    paddingHorizontal: 16,
  },
  categoryTabsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  categoryTab: {
    backgroundColor: '#F7FAFC',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    width: '23%',
    minHeight: 40,
    position: 'relative',
  },
  categoryTabSelected: {
    backgroundColor: '#0A4B4C',
    borderColor: '#0A4B4C',
  },
  categoryTabText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#4A5568',
    textAlign: 'center',
    flex: 1,
  },
  categoryTabTextSelected: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  categoryTabBadge: {
    backgroundColor: '#EA580C',
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 1,
    minWidth: 16,
    alignItems: 'center',
    position: 'absolute',
    top: -4,
    right: -4,
  },
  categoryTabBadgeText: {
    fontSize: 9,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  
  // Grid Layout Styles
  itemsGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
    justifyContent: 'space-around',
  },
  gridItemCard: {
    width: '30%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 8,
    marginBottom: 8,
    minHeight: 85,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 0,
  },
  gridItemTouchable: {
    flex: 1,
    position: 'relative',
  },
  gridItemImageContainer: {
    alignItems: 'center',
    marginBottom: 4,
  },
  gridItemPlaceholder: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F0F9FF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0,
  },
  gridItemIcon: {
    fontSize: 18,
  },
  gridItemInfo: {
    alignItems: 'center',
    marginBottom: 4,
    flex: 1,
    justifyContent: 'center',
  },
  gridItemName: {
    fontSize: 10,
    fontWeight: '700',
    color: '#1A202C',
    textAlign: 'center',
    marginBottom: 2,
    lineHeight: 12,
  },
  gridItemAmount: {
    fontSize: 8,
    color: '#A0AEC0',
    fontWeight: '400',
    textAlign: 'center',
  },
  gridItemStatusCircle: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  // Modal styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 12,
    marginVertical: 60,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 15,
    },
    shadowOpacity: 0.3,
    shadowRadius: 25,
    elevation: 15,
  },
  compactModalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginVertical: 120,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
  },
  modalContentContainer: {
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  modalHeader: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F4F8',
    backgroundColor: '#F8FAFC',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1A202C',
    letterSpacing: 0.5,
  },
  modalContent: {
    flex: 1,
    padding: 24,
    backgroundColor: '#FFFFFF',
  },
  inputContainer: {
    marginBottom: 24,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 24,
  },
  amountContainer: {
    flex: 1,
  },
  measurementContainer: {
    flex: 1,
  },
  inputLabel: {
    fontSize: 17,
    fontWeight: '700',
    color: '#2D3748',
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  textInput: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    fontSize: 16,
    color: '#2D3748',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    fontWeight: '500',
  },
  pickerContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  picker: {
    height: 50,
  },
  dateButton: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  dateButtonText: {
    fontSize: 16,
    color: '#2D3748',
  },
  deleteItemButton: {
    backgroundColor: '#EA580C',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 20,
  },
  deleteItemButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  
  // Professional Edit Modal Styles
  editModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editModalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 15,
  },
  editModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F4F8',
  },
  editModalItemPreview: {
    flex: 1,
  },
  editModalItemName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A202C',
    marginBottom: 4,
  },
  editModalItemSubtitle: {
    fontSize: 14,
    color: '#718096',
  },
  editModalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F7FAFC',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 16,
  },
  editModalCloseIcon: {
    fontSize: 18,
    color: '#718096',
  },
  editModalBody: {
    padding: 24,
  },
  editModalField: {
    marginBottom: 20,
  },
  editModalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#718096',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  editModalInput: {
    backgroundColor: '#F7FAFC',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#1A202C',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  editModalRow: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  editModalSelect: {
    backgroundColor: '#F7FAFC',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  editModalSelectText: {
    fontSize: 16,
    color: '#1A202C',
  },
  editModalSelectArrow: {
    fontSize: 12,
    color: '#718096',
  },
  editModalDateButton: {
    backgroundColor: '#F7FAFC',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
  },
  editModalDateIcon: {
    fontSize: 18,
    marginRight: 12,
  },
  editModalDateText: {
    fontSize: 16,
    color: '#1A202C',
    flex: 1,
  },
  editModalActions: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingBottom: 24,
    gap: 12,
  },
  editModalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  editModalDeleteButton: {
    backgroundColor: '#FFF5F5',
    borderWidth: 1,
    borderColor: '#FEB2B2',
  },
  editModalDeleteText: {
    color: '#E53E3E',
    fontSize: 16,
    fontWeight: '600',
  },
  editModalSaveButton: {
    backgroundColor: '#48BB78',
  },
  editModalSaveText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  editModalDatePicker: {
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    backgroundColor: '#F7FAFC',
  },
  editModalDateDone: {
    alignItems: 'center',
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  editModalDateDoneText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#48BB78',
  },
  
  // Measurement Picker Styles
  editModalMeasurementPicker: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '50%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -5,
    },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  editModalPickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  editModalPickerCancel: {
    fontSize: 16,
    color: '#E53E3E',
  },
  editModalPickerTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#1A202C',
  },
  editModalPickerDone: {
    fontSize: 16,
    color: '#48BB78',
    fontWeight: '600',
  },
  editModalPickerList: {
    paddingVertical: 8,
  },
  editModalPickerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F0F4F8',
  },
  editModalPickerItemText: {
    fontSize: 17,
    color: '#2D3748',
  },
  editModalPickerItemSelected: {
    color: '#48BB78',
    fontWeight: '600',
  },
  editModalPickerCheck: {
    fontSize: 18,
    color: '#48BB78',
    fontWeight: '600',
  },
  
  itemTouchable: {
    flex: 1,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  picker: {
    height: 50,
    color: '#000000',
  },
  pickerItem: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
  },
  expiryButtonContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 16,
    justifyContent: 'center',
  },
  expiryButton: {
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 8,
    minWidth: 90,
    alignItems: 'center',
  },
  expiryButtonSelected: {
    backgroundColor: '#0A4B4C',
    borderColor: '#0A4B4C',
  },
  expiryButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#4A5568',
    textAlign: 'center',
  },
  expiryButtonTextSelected: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  customExpiryButton: {
    backgroundColor: '#F7FAFC',
    borderColor: '#CBD5E0',
    borderStyle: 'dashed',
  },
  customExpiryContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    gap: 12,
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  customExpiryInput: {
    borderWidth: 2,
    borderColor: '#90EE90',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
    width: 100,
    textAlign: 'center',
    fontWeight: '600',
    color: '#2D3748',
    shadowColor: '#90EE90',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  customExpiryLabel: {
    fontSize: 16,
    color: '#4A5568',
    fontWeight: '600',
  },
  addModalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 30,
    paddingHorizontal: 20,
  },
  addModalCircularButton: {
    alignItems: 'center',
  },
  circularButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circularButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  cancelCircularButton: {
    backgroundColor: '#FF6B35',
    shadowColor: '#FF6B35',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  saveCircularButton: {
    backgroundColor: '#2D6A4F',
    shadowColor: '#2D6A4F',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  
  // Pantry Users Modal Styles
  closeButton: {
    position: 'absolute',
    top: 24,
    right: 20,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F7FAFC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 18,
    color: '#718096',
  },
  userCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F0F4F8',
  },
  userAvatar: {
    marginRight: 16,
  },
  userAvatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  userAvatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E6FFFA',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#81E6D9',
  },
  userAvatarText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2D6A4F',
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A202C',
    marginBottom: 4,
  },
  userEmail: {
    fontSize: 14,
    color: '#718096',
  },
  currentUserBadge: {
    fontSize: 14,
    color: '#22C55E',
    fontWeight: '500',
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    fontSize: 16,
    color: '#718096',
    textAlign: 'center',
  },
  // Tutorial Modal Styles
  tutorialOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  tutorialContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    width: '90%',
    height: '70%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
    overflow: 'hidden',
  },
  tutorialHeader: {
    backgroundColor: '#10B981',
    paddingVertical: 20,
    paddingHorizontal: 24,
    alignItems: 'center',
    position: 'relative',
  },
  tutorialCloseButton: {
    position: 'absolute',
    right: 16,
    top: 16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tutorialTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 8,
  },
  tutorialSubtitle: {
    fontSize: 16,
    color: '#ffffff',
    opacity: 0.9,
    textAlign: 'center',
  },
  tutorialContent: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 20,
  },
  tutorialStep: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 300,
  },
  tutorialIconContainer: {
    width: 100,
    height: 100,
    backgroundColor: '#F0FDF4',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 2,
    borderColor: '#E6FFFA',
  },
  tutorialStepTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F2937',
    textAlign: 'center',
    marginBottom: 16,
  },
  tutorialStepDescription: {
    fontSize: 16,
    color: '#6B7280',
    lineHeight: 24,
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  tutorialProgress: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  tutorialProgressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 4,
    backgroundColor: '#E5E7EB',
  },
  tutorialProgressDotActive: {
    backgroundColor: '#10B981',
    width: 24,
  },
  tutorialNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  tutorialButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    minWidth: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tutorialButtonPrimary: {
    backgroundColor: '#10B981',
  },
  tutorialButtonSecondary: {
    backgroundColor: '#F3F4F6',
  },
  tutorialButtonDisabled: {
    backgroundColor: '#E5E7EB',
    opacity: 0.6,
  },
  tutorialButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  tutorialButtonTextSecondary: {
    color: '#6B7280',
  },
  tutorialGetStartedButton: {
    backgroundColor: '#10B981',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 16,
    marginHorizontal: 24,
    marginBottom: 24,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  tutorialGetStartedText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
  },
  tutorialCloseText: {
    fontSize: 18,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  tutorialStepIcon: {
    fontSize: 40,
    color: '#10B981',
    fontWeight: 'bold',
    textShadowColor: 'rgba(16, 185, 129, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  tutorialLogoIcon: {
    width: 60,
    height: 60,
  },
  tutorialFeatures: {
    marginTop: 20,
    alignItems: 'flex-start',
    width: '100%',
  },
  tutorialFeature: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
    textAlign: 'left',
    paddingLeft: 8,
  },
  tutorialDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tutorialDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 4,
  },
  tutorialDotActive: {
    backgroundColor: '#10B981',
    width: 16,
  },
  tutorialPrevButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tutorialNextButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#10B981',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tutorialButtonPlaceholder: {
    width: 40,
    height: 40,
  },
  tutorialPrevText: {
    fontSize: 24,
    color: '#6B7280',
    fontWeight: 'bold',
  },
  tutorialNextText: {
    fontSize: 24,
    color: '#ffffff',
    fontWeight: 'bold',
  },
});

export default styles;
